services:

  chatbot_mysql:
    image: mysql:8.0
    container_name: chatbot_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"  
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - chatbot_network

  
  chatbot_web:
    build: .
    container_name: chatbot_flask_web
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DB_HOST=chatbot_mysql  
      - DB_USER=root  
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}  
      - DB_NAME=${DB_NAME}
    depends_on:
      - chatbot_mysql
    volumes:
      - ./logs:/app/logs
    networks:
      - chatbot_network

volumes:
  mysql_data:

networks:
  chatbot_network:
    driver: bridge